[workspace]
resolver = "2"
members = [
    "jwt",
    "snowflake-api",
    "snowflake-api/examples/tracing",
    "snowflake-api/examples/polars",
]

[patch.crates-io]
arrow = { git = "https://github.com/spiceai/arrow-rs.git", rev = "1e4a1d355a0b4c9ef917c5eec6ed2f88b670a0ff" } # branch: spiceai-59-patches (arrow 59.3.0)
arrow-array = { git = "https://github.com/spiceai/arrow-rs.git", rev = "1e4a1d355a0b4c9ef917c5eec6ed2f88b670a0ff" } # branch: spiceai-59-patches (arrow 59.3.0)
arrow-buffer = { git = "https://github.com/spiceai/arrow-rs.git", rev = "1e4a1d355a0b4c9ef917c5eec6ed2f88b670a0ff" } # branch: spiceai-59-patches (arrow 59.3.0)
arrow-cast = { git = "https://github.com/spiceai/arrow-rs.git", rev = "1e4a1d355a0b4c9ef917c5eec6ed2f88b670a0ff" } # branch: spiceai-59-patches (arrow 59.3.0)
arrow-json = { git = "https://github.com/spiceai/arrow-rs.git", rev = "1e4a1d355a0b4c9ef917c5eec6ed2f88b670a0ff" } # branch: spiceai-59-patches (arrow 59.3.0)
arrow-ipc = { git = "https://github.com/spiceai/arrow-rs.git", rev = "1e4a1d355a0b4c9ef917c5eec6ed2f88b670a0ff" } # branch: spiceai-59-patches (arrow 59.3.0)
arrow-ord = { git = "https://github.com/spiceai/arrow-rs.git", rev = "1e4a1d355a0b4c9ef917c5eec6ed2f88b670a0ff" } # branch: spiceai-59-patches (arrow 59.3.0)
arrow-schema = { git = "https://github.com/spiceai/arrow-rs.git", rev = "1e4a1d355a0b4c9ef917c5eec6ed2f88b670a0ff" } # branch: spiceai-59-patches (arrow 59.3.0)
