[workspace]
resolver = "2"
members = [
    "jwt",
    "snowflake-api",
    "snowflake-api/examples/tracing",
    "snowflake-api/examples/polars",
]

[patch.crates-io]
arrow = { git = "https://github.com/spiceai/arrow-rs.git", rev = "16974504b7f1776971f4fb20bbe355b09d090a0d" }        # arrow 59.3.0 (spiceai-59-patches)
arrow-array = { git = "https://github.com/spiceai/arrow-rs.git", rev = "16974504b7f1776971f4fb20bbe355b09d090a0d" }  # arrow 59.3.0 (spiceai-59-patches)
arrow-buffer = { git = "https://github.com/spiceai/arrow-rs.git", rev = "16974504b7f1776971f4fb20bbe355b09d090a0d" } # arrow 59.3.0 (spiceai-59-patches)
arrow-cast = { git = "https://github.com/spiceai/arrow-rs.git", rev = "16974504b7f1776971f4fb20bbe355b09d090a0d" }   # arrow 59.3.0 (spiceai-59-patches)
arrow-json = { git = "https://github.com/spiceai/arrow-rs.git", rev = "16974504b7f1776971f4fb20bbe355b09d090a0d" }   # arrow 59.3.0 (spiceai-59-patches)
arrow-ipc = { git = "https://github.com/spiceai/arrow-rs.git", rev = "16974504b7f1776971f4fb20bbe355b09d090a0d" }    # arrow 59.3.0 (spiceai-59-patches)
arrow-ord = { git = "https://github.com/spiceai/arrow-rs.git", rev = "16974504b7f1776971f4fb20bbe355b09d090a0d" }    # arrow 59.3.0 (spiceai-59-patches)
arrow-schema = { git = "https://github.com/spiceai/arrow-rs.git", rev = "16974504b7f1776971f4fb20bbe355b09d090a0d" } # arrow 59.3.0 (spiceai-59-patches)
